### ISSUE TITLE
Gruppen / Berechtigungen - API

### ISSUE THREAD

**Issue by iTitus** [hhu-propra2/abschlussprojekt-it-bois#15]
Wir als Materialsammlung möchten gerne bei euch anfragen um für einen User in einer bestimmten Gruppe die Berechtigungen/Rollen abzufragen.

material1: hhu-propra2/abschlussprojekt-mopse#40
gruppen1: hhu-propra2/abschlussprojekt-die-senioren#2
material2: hhu-propra2/abschlussprojekt-team-git-gud#12
gruppen2: hier

**Comment by killerber4t** [comment]
Eigentlich liegen die Rollen und Berechtigungen im KeyCloak. Was genau meint ihr denn?

**Comment by iTitus** [comment]
Ihr müsst die Berechtigungen ja auch pro Gruppe verwalten.
Ein User kann `Student` in einem Kurs sein und und `Organisator` in einer Lerngruppe.

Wenn er Organisator in einer Lerngruppe ist kann er da natürlich frei schalten und walten und Dateien hochladen/löschen etc.
Als Student im Kurs darf er dort wahrscheinlich keine Dateien hochladen.
