### ISSUE TITLE
wird api-user zur Kommunikation mit protfolios benötigt?

### ISSUE THREAD

**Issue by mkasimd** [hhu-propra2/abschlussprojekt-it-bois#77]
Hallo Leute, wird api-user zur Kommunikation zwischen unseren Systemen benötigt, oder weiterhin nur simples HTTP GET via Pfad?

**Comment by mkasimd** [comment]
Weitere Nachfrage:

Im JSON gibt es folgendenm Felder:

```
{
  // [...]
  "roles": {},
  "type": "LECTURE"
   // [...]
```

Was genau wird da gespeichert? Wieso hat eine Gruppe Rollen, und wofür steht "type"? Werden dort die expliziten Veranstaltungen (z.B. "Propra2") gespeichert, oder einfach nur eine Kategorie (z.B. "Vorlesung", "Seminar")?

**Comment by LukasEttel** [comment]
type steht dafür ob eine Gruppe eine Vorlesung ist, oder zu einer gehört. Da wir Vorlesungen besonders behandeln. parant ist die Vorlesung zu der gruppe gehört.

in roles werden werden die mitglieder auf ihre rolle in ihrer gruppe gemapped

**Comment by ChUrl** [comment]
> Hallo Leute, wird api-user zur Kommunikation zwischen unseren Systemen benötigt, oder weiterhin nur simples HTTP GET via Pfad?

Jo, die Api ist gesichert, das heißt der Aufruf muss wie in der Keycloak-demo erfolgen damit die Rolle api_user erfüllt wird.

**Comment by mkasimd** [comment]
Hey, wegen den responses noch einmal. Wie wollt ihr uns übermitteln, wenn eine Gruppe gelöscht wurde?

**Comment by LukasEttel** [comment]
zur zeit wollen wir das so handeln, dass wir euch einfach weiterhin die gruppe schicken, aber alles außer die die group-id null oder leer ist

**Comment by mkasimd** [comment]
okay. Wäre es eigentlich nicht besser, wenn ihr uns die Events schickt statt eine Liste von Gruppen, oder ist das eine Vorgabe?

**Comment by ChUrl** [comment]
Ne das ist keine Vorgabe, aber wir haben uns für vollständige Gruppen entschieden, weil ihr euch so die Gruppen nicht selbst rekonstruieren müsst.
